const data = [
    {
        id: 1,
        childrenKeys: [],
        collegeKeys: [],
        fatherName: "Mohammad bin",
        motherName: "Begum Hafiz",
        occupationKeys: [],
        phoneKeys: [],
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        userImage: undefined,
    },
    {
        id: 2,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "syed.fhafiz@gmail.com",
        familyName: "salmaul",
        fatherName: "Fatehhi bin",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Mahira Khan",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Ismail Darbaar",
        village: undefined,
        visitedMasjid: true,
        visitedPak: true,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    },
    {
        id: 3,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "abdul hafiz",
        familyName: "abdul",
        fatherName: "hassan ali",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Sania Mirza",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Shahid Afridi",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    },
    {
        id: 4,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "abdul hafiz",
        familyName: "Rafi mohd.",
        fatherName: "Ramesh Gupta",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Rukkaiya Ali",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Hassan Hafiz",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    },
    {
        id: 5,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "abdul hafiz",
        familyName: "abdul",
        fatherName: "Shohaib Akhtar",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Mehnaz",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Suleman sheik",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    },
    {
        id: 6,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "abdul hafiz",
        familyName: "abdul",
        fatherName: "Sakeb Akhtar",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Sultana zafar",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Bismil rehman",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    },
    {
        id: 7,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "abdul hafiz",
        familyName: "abdul",
        fatherName: "Mohd. Azhar",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Mahira begum",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Munnaf patel",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    },
    {
        id: 8,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "17/09/1990",
        email: "abdul hafiz",
        familyName: "abdul",
        fatherName: "Bin ilahi",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Maya Ali",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Arshad Humza",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    }, {
        id: 9,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "abc.hafiz@gmail.com",
        familyName: "abdul",
        fatherName: "Takeshi bagchi",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Noor jahan",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Sheik Ehtesham",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    }, {
        id: 10,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "abdul hafiz",
        familyName: "abdul",
        fatherName: "Mohammad bin",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Maya Ali",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Abdul Hafiz",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    }, {
        id: 11,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "abdul hafiz",
        familyName: "abdul",
        fatherName: "Sulemaan tyagi",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Meher Afroz",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Abdul Hafiz",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    }, {
        id: 12,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "abdul hafiz",
        familyName: "abdul",
        fatherName: "Sulemaan tyagi",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Zubeda Khan",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Abdul Hafiz",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    }, {
        id: 13,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "abdul hafiz",
        familyName: "abdul",
        fatherName: "Mohammad bin",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Maya Ali",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Abdul Hafiz",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    }, {
        id: 14,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "abdul hafiz",
        familyName: "abdul",
        fatherName: "Mohammad bin",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Maya Ali",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Abdul Hafiz",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    }, {
        id: 15,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "abdul hafiz",
        familyName: "abdul",
        fatherName: "Mohammad bin",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Maya Ali",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Abdul Hafiz",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    }, {
        id: 16,
        aadharNo: 546848463453,
        associatedWithArmy: undefined,
        beenOGW: undefined,
        block: undefined,
        childrenKeys: [],
        collegeKeys: [],
        district: undefined,
        dob: "12/12/1985",
        email: "mainak hafiz",
        familyName: "abdul",
        fatherName: "turram bin",
        hasPOKRelatives: undefined,
        hasSocialMedia: undefined,
        houseNo: undefined,
        mohalla: undefined,
        motherName: "Maya Ali",
        occupationKeys: [],
        panchayat: undefined,
        phoneKeys: [],
        politicalAffiliation: undefined,
        schoolKeys: [],
        siblingAddress: ['fhttfhtf'],
        siblingDob: ["15/04/1990"],
        siblingKeys: [0],
        siblingName: ['fhfdh'],
        siblingOccupation: ['thfthft'],
        siblingRelation: ['sister'],
        spouseKeys: [],
        tehsil: undefined,
        userImage: undefined,
        userName: "Mainak Hafiz",
        village: undefined,
        visitedMasjid: undefined,
        visitedPak: undefined,
        visitedSouthKashmir: undefined,
        ward: undefined,
        wasArrested: undefined
    },
]

module.exports = data;